import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create AusData App',
  description: 'Generated by create AusData app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex justify-center items-center min-h-screen ${inter.className}`} style={{background: "#151515"}}>
        <div className="flex justify-center items-center containerLightEdge">
          {children}
        </div>
      </body>
    </html>
  )
}
